package org.trybunal.examples.probe;

import java.util.List;

/**
 * One row of the probe's findings. Pure data — the probe collects these
 * and a separate routine renders them as Markdown into
 * {@code build/context-limits.md}.
 *
 * <p>{@code safeChars} is the largest user-message size (in characters)
 * the probe successfully sent before the next step-up failed.
 * {@code ceilingChars} is the size at which Ollama errored out — empty
 * placeholder, non-2xx, or 60-second wall-clock timeout. Both are
 * derived from a deterministic, repeatable binary search so two runs
 * against the same Ollama daemon and same fixture seed produce
 * identical numbers.</p>
 *
 * @param model        Ollama model name (e.g. {@code "gemma4:26b"})
 * @param numCtx       configured {@code num_ctx} used for the probe
 * @param safeChars    largest accepted user-message size in chars
 * @param approxTokens approximate token count for {@code safeChars} (chars / 4)
 * @param ceilingChars first failing size in chars; {@code -1} if none seen
 * @param failureMode  one of {@code "empty-placeholder"}, {@code "http-error"},
 *                     {@code "timeout"}, or {@code "none"} when no ceiling was hit
 */
public record ContextProbeReport(
        String model,
        int numCtx,
        int safeChars,
        int approxTokens,
        int ceilingChars,
        String failureMode
) {

    /** Markdown table renderer. Header + one row per report, GFM-friendly. */
    public static String toMarkdownTable(List<ContextProbeReport> rows) {
        StringBuilder sb = new StringBuilder();
        sb.append("# Ollama Context-Window Probe Results\n\n");
        sb.append("Empirical safe / ceiling message sizes per model. Generated by\n");
        sb.append("`examples:probe-context-limit:run`. Numbers are deterministic given\n");
        sb.append("the same Ollama daemon, model, and `num_ctx`.\n\n");
        sb.append("| Model | num_ctx | Safe chars | ~Tokens | Ceiling chars | Failure mode |\n");
        sb.append("|---|---:|---:|---:|---:|---|\n");
        for (ContextProbeReport r : rows) {
            sb.append("| `").append(r.model()).append("` | ")
              .append(r.numCtx()).append(" | ")
              .append(r.safeChars()).append(" | ")
              .append(r.approxTokens()).append(" | ")
              .append(r.ceilingChars() < 0 ? "—" : Integer.toString(r.ceilingChars()))
              .append(" | ")
              .append(r.failureMode())
              .append(" |\n");
        }
        return sb.toString();
    }
}
